// Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {
    let sum = 0, num_1 = 1, num_2 = 2;
    while(num_2 <= n){
      if(num_2 % 2 === 0) sum += num_2;
      let next_num = num_1 + num_2;
      num_1 = num_2;
      num_2 = next_num;
    }
    return sum;
  }
  
  fiboEvenSum(10);